// Verbo + Substantivo
// let corSite ='Azul'
// function resetaCor(cor,tonalidade){
//     corSite=cor + ' ' +  tonalidade;
// };
// console.log(corSite);
// resetaCor("verde" ,"claro");
// console.log(corSite);

// atividade fazer funcoes

// let CorOlho = "Verde";
// function resetaCor(cor){
//     CorOlho = cor;  
// };
// console.log(CorOlho);




// console.log(corSite);
// resetaCor('Vermelho');
// console.log(corSite);

// chamaFunções
// console.log(corSite);
// resetaCor();

// Tipos de Funcoes no JavaScript Aula 08

// Realizar uma tarefa ,não devolve nada 
function dizerNome(){
  console.log('Patricia');
}
dizerNome();
// faz um calculo ou operação e retorna algo
function MultiplicarporDois(valor){
    return  valor *2;
}
// console.log(MultiplicarporDois(5))
let resultado = MultiplicarporDois(5);
console.log(resultado);